Added APPLICATION_TYPE var; added qt5-qtwebkit-devel package for capybara-webkit.

diff --git a/2.5/s2i/bin/run b/2.5/s2i/bin/run
--- a/2.5/s2i/bin/run
+++ b/2.5/s2i/bin/run
@@ -1,41 +1,44 @@
 #!/bin/bash
 
-# function is_puma_installed() {
-#   [ ! -f Gemfile.lock ] && return 1
-#   grep ' puma ' Gemfile.lock >/dev/null
-# }
+function is_puma_installed() {
+  [ ! -f Gemfile.lock ] && return 1
+  grep ' puma ' Gemfile.lock >/dev/null
+}
 
-# set -e
+set -e
 
-# function check_number() {
-#   if [[ ! "$2" =~ ^[0-9]+$ ]]; then
-#     echo "$1 needs to be a non-negative number"
-#     exit 1
-#   fi
-# }
-# check_number PUMA_WORKERS     "${PUMA_WORKERS:-0}"
-# check_number PUMA_MIN_THREADS "${PUMA_MIN_THREADS:-0}"
-# check_number PUMA_MAX_THREADS "${PUMA_MAX_THREADS:-0}"
+function check_number() {
+  if [[ ! "$2" =~ ^[0-9]+$ ]]; then
+    echo "$1 needs to be a non-negative number"
+    exit 1
+  fi
+}
 
-# export RACK_ENV=${RACK_ENV:-"production"}
+if [ "$APPLICATION_TYPE" = "compliance-backend" ]; then
+	check_number PUMA_WORKERS     "${PUMA_WORKERS:-0}"
+	check_number PUMA_MIN_THREADS "${PUMA_MIN_THREADS:-0}"
+	check_number PUMA_MAX_THREADS "${PUMA_MAX_THREADS:-0}"
 
-# if is_puma_installed; then
-#   export_vars=$(cgroup-limits) ; export $export_vars
+	export RACK_ENV=${RACK_ENV:-"production"}
 
-#   exec bundle exec "puma --config ../etc/puma.cfg"
-# else
-#   echo "You might consider adding 'puma' into your Gemfile."
+	if is_puma_installed; then
+	  export_vars=$(cgroup-limits) ; export $export_vars
 
-#   if bundle exec rackup -h &>/dev/null; then
-#     if [ -f Gemfile ]; then
-#       exec bundle exec "rackup -E ${RAILS_ENV:-$RACK_ENV} -P /tmp/rack.pid --host 0.0.0.0 --port 8080"
-#     else
-#       exec rackup -E "${RAILS_ENV:-$RACK_ENV}" -P /tmp/rack.pid --host 0.0.0.0 --port 8080
-#     fi
-#   else
-#     echo "ERROR: Rubygem Rack is not installed in the present image."
-#     echo "       Add rack to your Gemfile in order to start the web server."
-#   fi
-# fi
+	  exec bundle exec "puma --config ../etc/puma.cfg"
+	else
+	  echo "You might consider adding 'puma' into your Gemfile."
 
-bundle exec racecar ComplianceReportsConsumer
+	  if bundle exec rackup -h &>/dev/null; then
+	    if [ -f Gemfile ]; then
+	      exec bundle exec "rackup -E ${RAILS_ENV:-$RACK_ENV} -P /tmp/rack.pid --host 0.0.0.0 --port 8080"
+	    else
+	      exec rackup -E "${RAILS_ENV:-$RACK_ENV}" -P /tmp/rack.pid --host 0.0.0.0 --port 8080
+	    fi
+	  else
+	    echo "ERROR: Rubygem Rack is not installed in the present image."
+	    echo "       Add rack to your Gemfile in order to start the web server."
+	  fi
+	fi
+elif [ "$APPLICATION_TYPE" = "compliance-consumer" ]; then
+	bundle exec racecar ComplianceReportsConsumer
+fi
